### ISSUE TITLE
Bug: certificate-authority for external-admin-kubeconfig should match the certificateIssuer configured in values.yaml

### ISSUE THREAD

**Issue by ErwanDL** [kcp-dev/helm-charts#100]
The values.yaml of the KCP Helm chart allow configuring a custom (server) certificate issuer for the front-proxy: https://github.com/kcp-dev/helm-charts/blob/main/charts/kcp/values.yaml#L117-L121

However, the `certificate-authority` field of the external-admin-kubeconfig is hardcoded, instead of pointing to the CA cert of the configured certificate issuer: https://github.com/kcp-dev/helm-charts/blob/main/charts/kcp/templates/server-kubeconfigs.yaml#L50

I am not exactly sure how to fix this. I guess we need to both:
- mount the custom CA cert in server-deployment.yaml
- parameterize server-kubeconfigs.yaml so that `certificate-authority` points to this mounted CA cert

This would require some additions to values.yaml if I'm not mistaken. Does this sound reasonable?

**Comment by embik** [comment]
Assuming the fix is backwards-compatible (which I don't see why it wouldn't) we can absolutely push it as 0.8.1.
