### ISSUE TITLE
Remove the extraFlags kcp chart parameter

### ISSUE THREAD

**Issue by kylape** [kcp-dev/helm-charts#16]
This was just a hack to address some backwards-incompatible flag changes in kcp.  In the future kcp releases should be better coordinated with the helm chart releases.

**Comment by xrstf** [comment]
@mjudeikis @embik WDYT about this? Leave `extraFlags` to make customizations possible, or remove it to prevent users from fiddling with the flags?

**Comment by mjudeikis** [comment]
I dont think we have way to provide feature-gates now:
```
  extraFlags:
  - --feature-gates=WorkspaceMounts=true
```
So we need it until we get it into charts too

**Comment by mjudeikis** [comment]
So to remove this we need add ability to provide featuregates list first
