### ISSUE TITLE
 x509: certificate is valid for ingress.local, not <external_hostname>.com

### ISSUE THREAD

**Issue by yogesh-reddy** [kcp-dev/helm-charts#31]
Installed the latest helm chart. 
and followed https://github.com/kcp-dev/helm-charts/pull/30 to create admin kubeconfig.
When tried to access kcp with the generated configs..

```
kubectl ws create ws-1 --enter
Error: Post "https://**.com:443/clusters/root/apis/tenancy.kcp.dev/v1beta1/workspaces": x509: certificate is valid for ingress.local, not ***.com
```

**Comment by yogesh-reddy** [comment]
external hostname is set externally resolvable DNS name.

> Can you provide the values used here - is `externalHostname` set to `ingress.local` or `***.com`? (where `***.com` is an externally resolvable DNS name pointing to the ingress endpoint for the cluster)

**Comment by hardys** [comment]
I think ingress-nginx must be using `ingress.local` for the ingress endpoint CA cert? 

I'm not familiar with how to fix that but perhaps @mjudeikis can suggest something as it relates to the work in https://github.com/kcp-dev/helm-charts/pull/27/

**Comment by yogesh-reddy** [comment]
@hardys  @mjudeikis  here is how I tried the kcp installation

- Installed nginx ingress
-  Added a DNS entry for load balancer URL for ingress controller
-  installed a chart by providing the DNS name as an external hostname and enabling ingress
- tried accessing the kcp with kubeconfig generated using the step in #30 

Let me know if anything different is expected

**Comment by yogesh-reddy** [comment]
Also @hardys i was looking at ingress resources..
looks like the secret name is not set.

should spec of Tls hosts contain this secret name ?
`secretName: kcp-front-proxy-cert`

**Comment by mjudeikis** [comment]
I know ingress might be with a few hiccups now and secret name might be wrong. 
I have bunch of changes in my fork, but I want to merge #27 first. TL:DR: There might be issues :)

**Comment by yogesh-reddy** [comment]
@mjudeikis  found the issue. the ingress was not honoring the certs .. so we need some extra configurations in ingress to honor the tls certs and add some lua scripting to forward these. i am able to access the kcp locally now.
