### ISSUE TITLE
hack/kind-setup.sh is too specific about where to find kind

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/helm-charts#50]
That script insists on what directory to find the `kind` command in, but kind has multiple ways to install and they do not all put the executable where the script insists on finding it.

**Comment by xrstf** [comment]
Since #57 we just use `command kind` to find `kind` whereever: https://github.com/kcp-dev/helm-charts/blob/main/hack/kind-setup.sh#L8
