### ISSUE TITLE
Update included etcd StatefulSet version

### ISSUE THREAD

**Issue by embik** [kcp-dev/helm-charts#72]
The `etcd` StatefulSet is on a 3.5 version that is quite old. We should update it to a more recent 3.5.x patch release due to some important fixes in etcd.

However, this will require reworking the `command` because it uses `/bin/sh`, and etcd switched to distroless as base image in one of the 3.5 patch releases. `/bin/sh` does not exist in distroless and therefore we need to change the `StatefulSet` to not do any shell "scripting".

**Comment by luxas** [comment]
Do you think the solution proposed in https://github.com/kcp-dev/helm-charts/issues/94#issue-2448460334 would work, i.e. just use containerspec `env` instead of the CLI args?

How do I verify stuff keeps working? Are there e2e jobs in CI covering this codepath?

**Comment by embik** [comment]
> just use containerspec env instead of the CLI args?

I think that should work. You might even get away with doing the templating of the peer list directly in `--initial-cluster`, but an environment variable should do the trick as well and would keep things more readable.

> How do I verify stuff keeps working? Are there e2e jobs in CI covering this codepath?

There currently is a job that checks if the Kubernetes resources generated by Helm in the default configuration is valid, but no e2e test of the setup. If you install your version of the Helm chart onto a cluster and etcds start and kcp runs without crashing, things should be okay.

That being said, with this specific change I'd be curious if previous installations can be upgraded, but I'm happy to assist there and also run a little upgrade test if needed.

**Comment by luxas** [comment]
Thanks, I'll send a small PR for that (probably today then), and see if things keep working 👍

**Comment by luxas** [comment]
Sent PR now, sorry, got side-tracked with other things end of last week 😅
