### ISSUE TITLE
Newer versions of etcd uses distroless, i.e. /bin/sh is not available for etcd shard

### ISSUE THREAD

**Issue by luxas** [kcp-dev/helm-charts#94]
etcd 3.5.7 moved to use a distroless base image, so `/bin/sh` cannot be used anymore here: https://github.com/kcp-dev/helm-charts/blob/a8454bb85f19da71bfb9074d54deff5bb600aa68/charts/shard/templates/etcd-statefulset.yaml#L45

Could we convert the `PEERS` environment variable to be set by the PodSpec instead of within the arguments; and execute etcd binary directly perhaps?

**Comment by embik** [comment]
Hey @luxas, I also brought this up in #72. We'd absolutely be open to converting things so they work without `/bin/sh`, none of the maintainer got to it yet though.

**Comment by luxas** [comment]
Sorry, didn't realize #72 was the same issue, I'll close this and move to #72. Thanks!

**Comment by embik** [comment]
No worries at all!
